services:
  - docker

jobs:
  include:
    - stage: macos-test
      os: osx
      before_install:
        - brew install gmp
      script: docker run -it -v `pwd`:/opt/my-project -w /opt/my-project tf-encrypted/tf-big /bin/bash -c "make test"
