services:
  - docker

jobs:
  include:
    - stage: macos-test
      os: osx
      before_install: |
        curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        bash Miniconda3-latest-MacOSX-x86_64.sh -b -f
        ../miniconda3/bin/conda create -n py35 python=3.5 2> /dev/null || true
        ../miniconda3/envs/py35/bin/python -m venv venv
        . venv/bin/activate
        HOMEBREW_NO_AUTO_UPDATE=1 brew tap bazelbuild/tap
        HOMEBREW_NO_AUTO_UPDATE=1 brew install gmp azelbuild/tap/bazel
      script: |
        make test