services:
  - docker

jobs:
  include:
    - stage: linux-test
      before_install:
        - docker build -t tf-encrypted/tf-big .
      script: |
        docker run -it -v `pwd`:/opt/my-project -w /opt/my-project tf-encrypted/tf-big /bin/bash -c "make test"
