version: 2

jobs:
  build:
    docker:
      - image: tensorflow/tensorflow:custom-op
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install gmp deps
          command: |
            wget https://gmplib.org/download/gmp/gmp-6.1.2.tar.xz
            tar -xf gmp-6.1.2.tar.xz
            cd gmp-6.1.2 && ./configure --with-pic --enable-cxx --enable-static --disable-shared && make && make check && sudo make install
      - run:
          name: run tests and build the docs
          command: |
            export LD_LIBRARY_PATH=/usr/local
            make test